Template.cart.helpers({
  // TODO pull cart items from database
  cartItems: [{
    productId: '1',
    description: "Aunt Ruby's Green Tomato",
    pic: "/images/user-images/AuntRubyTomato.png",
    unitType: "each",
    unitPrice: 2.20,
    currency: 'USD',
    vendorUserId: '2',
    vendorName: 'Anthony Apple',
    vendorLink: '/profile/2',
    quantity: 3,
    itemTotalPrice: 6.60,
  }, {
    productId: '2',
    description: "Scarlet Nantes Carrot",
    pic: "/images/user-images/ScarletNantesCarrot.png",
    unitType: "pounds",
    unitPrice: 1.50,
    currency: 'USD',
    vendorBusinessId: '2',
    vendorName: 'XYZ Compost Removal',
    vendorLink: '/business/2',
    quantity: 2,
    itemTotalPrice: 3.00,
  }, {
    productId: '3',
    description: "Little Gem Lettuce",
    pic: "/images/user-images/LittleGemLettuce.png",
    unitType: "5 pound bags",
    unitPrice: 10.50,
    currency: 'USD',
    vendorBusinessId: '2',
    vendorName: 'XYZ Compost Removal',
    vendorLink: '/business/2',
    quantity: 4,
    itemTotalPrice: 42.00,
  }],
});
